#!/usr/bin/env nomad
(let space " ")

(letfun char_to_morse (char)
	(switch (lower char)
		(space " / ")
		("a" ".-")
		("b" "-...")
		("c" "-.-.")
		("d" "-..")
		("e" ".")
		("f" "..-.")
		("g" "--.")
		("h" "....")
		("i" "..")
		("j" ".---")
		("k" "-.-")
		("l" ".-..")
		("m" "--")
		("n" "-.")
		("o" "---")
		("p" ".--.")
		("q" "--.-")
		("r" ".-.")
		("s" "...")
		("t" "-")
		("u" "..-")
		("v" "...-")
		("w" ".--")
		("x" "-..-")
		("y" "-.--")
		("z" "--..")
		(_ (throw (sprint "Cannot convert '" char "' to morse code")))))

(letfun text_to_morse (text) 
	(foldl (lambda (acc char)
		(sprint acc " " (char_to_morse char)))
	"" (chars text)))

(if (= args 1)
	(do
		(println "Usage: morse.nomad <words...>")
		(exit 1))
		
	(foreachi (lambda (m i)
		(if (= i 0)
			(print (text_to_morse m))
			(print " / " (text_to_morse m))))
	(cdr args)))
